### ISSUE TITLE
@HaraldZealot  question

### ISSUE THREAD

**Issue by Metamophose** [BSU2013gr0209web/ZhukovskyVV02#2]
Каким образом удалить папки именно на гитхабе? rm -rf удаляет локально cached вроде просто убирает из наблюдения.
И вопрос по лабе. Почему в функции changebuttons при четном входе(т.е когда одна кнопка уже открыта), функция swap не проходить ,а сразу же идет на if проверку текстового значения и ,не смотря на задержку, происходит swapback?

**Comment by HaraldZealot** [comment]
git rm імя файла
потым закаміціць і запушыць

**Comment by Metamophose** [comment]
А касательно лабы не подскажите?

**Comment by HaraldZealot** [comment]
Магчыма гэта звязана з асінхроннасцю працы сігналаў. Праўда я гледзечы па кодзе не бачу там гэтага.

Але вы першапачаткова выбралі неслушнае архітэктурнае рашэнне. Напрыклад варта былу зрабіць кастомную кнопку, якая магла б паказваць ці не паказваць лічбы, і ўжо працаваць з масівам такіх кнопак.

**Comment by Metamophose** [comment]
Учту на будущее, спасибо!
